#!/usr/local/bin/python3

import os
import binascii
import codecs
import gzip

f = 'HelveticaNeueLTStd-Roman.otf'

fh = open(f, 'rb')
data = fh.read()
fh.close()

fh = open('test.gzip', 'wb')
fh.write(gzip.compress(data))
fh.close()
