#!/usr/bin/python

import subprocess
import re

ifconfig = ['ifconfig', '-u', '-a']

if_ret = subprocess.Popen(ifconfig, stdout=subprocess.PIPE).communicate()[0]
if_ret = re.sub("(?m)\n\t", " ", if_ret)

r = re.compile("(?mx) (^\S+): .* \tinet\s ([0-9.]+)")
m = r.findall(if_ret)

for i in m:
	print i[0], i[1]

