#!/usr/bin/env python

import sys
import pipes
import subprocess

p = pipes.Template()

cmd = ['cat', sys.argv[1]]

cat = subprocess.Popen(cmd, stdout=subprocess.PIPE)
ii = "convert -background black -fill white -interline-spacing 2 -pointsize 40 -page 1920x1080+10+10 text:- -flatten %s" % sys.argv[2]
cmd = ii.split()
print ii

output = subprocess.check_output(cmd, stdin=cat.stdout)
cat.wait()
