#!/usr/bin/python

import os
import re
import argparse

class LSF(object):
    def __init__(self, parser):
        self.dirs = parser.parse_args().directory
        self.sequences = {};

        for dir in self.dirs:
            self.parse_directory(dir)

        self.format_list()

    def parse_directory(self, dir):
        filelist = sorted(os.listdir(dir))
        for file in filelist:
            frame = re.search(r'(\d+)([._]*\w+)$', file)
            if (frame):
                prefix = file.split(frame.group(0))[0]
                framenum = frame.group(1)
                extension = frame.group(2)

                if prefix in self.sequences:
                    self.sequences[prefix]['frames'].append(framenum)
                else:
                    self.sequences[prefix] = {}
                    self.sequences[prefix]['frames'] = [framenum]
                    self.sequences[prefix]['ext'] = extension

    def format_list(self):
        for prefix in self.sequences:
            extension = self.sequences[prefix]['ext']
            frames = sorted(self.sequences[prefix]['frames'], key=int)

            pad = len(frames[0]);
            currframe = frames[0]
            allframes = '[%d' % int(currframe)
            lastframe = int(frames[-1])

            for i in frames:
                d = int(i)
                if d > int(currframe):
                    if d - 1 != int(currframe):
                        allframes = allframes + '-%0*d,%0*d' % (pad, int(currframe), pad, d)

                    currframe = i

                if d == lastframe:
                    allframes = allframes + '-%0*d]' % (pad, d)

            self.sequences[prefix]['string'] = "%s%s%s" % (prefix, allframes, extension)
            print self.sequences[prefix]['string']

if __name__ == "__main__":
    pwd = os.getcwd()

    parser = argparse.ArgumentParser(
        prog='lsf',
        description='List Image Sequences.',
        formatter_class=argparse.RawTextHelpFormatter
    )

    parser.add_argument('directory', nargs='*', help='List of one or more directories to search.\nDefault: %s' % pwd, default=[pwd])

    LSF(parser)
